/**
 * A built report, rendered to something you can send to somebody.
 *
 * **Pure functions over a built report, for the reason `buildStages()` is pure.** These take the
 * object `reportBuild` returns and give back a string; they open no file, read no `db`, and know
 * nothing about S3. That is what lets `scripts/verify-report-export.js` assert what a report
 * renders to without a bucket, a network or a published graph — and an exporter that can only be
 * checked by exporting is an exporter nobody checks.
 *
 * **What is exported is a snapshot, and it says so.** The section's rule is that a saved report is
 * a question re-asked, never a stored result — so a file, which *is* a stored result, has to be
 * honest about being one. Every export carries the moment it was generated, the frame it was
 * generated under, and the published graph that answered it, because a figure detached from those
 * three is a number with no question attached.
 *
 * No PDF here, deliberately. Server-side PDF means a headless browser (~40 transitive packages and
 * a Chromium download) through an audit gate that fails on any advisory at `low`. The HTML carries
 * a print stylesheet instead, so *Print → Save as PDF* produces the same document with page breaks
 * that fall between blocks. If a real PDF pipeline is ever wanted, that is a dependency decision to
 * make on its own terms rather than a side effect of adding an export button.
 */

/* ---------------- shared ---------------- */

const esc = (v) =>
  String(v ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')

/** The table-shaped blocks. A chart is derived from rows; these *are* rows. */
const TABULAR = new Set(['table', 'facilities', 'quarterly', 'traces'])

/** `2026-08-18T16-40-02Z` — sortable, and legal in an object key on every platform. */
export const stamp = (iso) => iso.replace(/\.\d+/, '').replace(/:/g, '-')

/**
 * The object key an export lands on.
 *
 * Named for a person reading a bucket listing: the report, then when it was generated. The id
 * rather than the heading, because a heading holds spaces and punctuation and a key that needs
 * decoding to read is a key nobody reads.
 */
export const exportKey = (report, format, iso) =>
  `exports/${report.report_id}-${stamp(iso)}.${format}`

/* ---------------- CSV ---------------- */

/**
 * RFC 4180: quote when the value holds a comma, a quote or a newline, and double an inner quote.
 * Naive `join(',')` corrupts exactly the fields worth exporting — a facility name with a comma in
 * it splits into two columns and every later column shifts by one, silently.
 */
const cell = (v) => {
  const s = v === null || v === undefined ? '' : String(v)
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}

/**
 * The report's tables, one section each.
 *
 * **Every tabular block is emitted, not just the first.** A report holds several, and exporting
 * one of them would be a silent truncation of the others — the rule the charts follow with their
 * "no cap is silent" note. Sections are separated by a blank line and headed by the block's own
 * title, which is what a spreadsheet shows when it opens the file.
 *
 * Charts are deliberately absent: every one of them is computed from a table that is already here,
 * so writing their series again would put two copies of one figure in a file somebody will edit.
 */
export function toCsv(report, { generatedAt, generatedBy } = {}) {
  const lines = []

  lines.push(cell(report.heading))
  if (report.subtitle) lines.push(cell(report.subtitle))
  lines.push('')
  lines.push(['Generated', cell(generatedAt ?? '')].join(','))
  if (generatedBy) lines.push(['Generated by', cell(generatedBy)].join(','))
  lines.push(['Question', cell(report.question ?? '')].join(','))
  lines.push(['Scope', cell(report.assumptions?.scope ?? report.frame?.scope ?? '')].join(','))
  lines.push(['Measure', cell(report.assumptions?.measure ?? report.frame?.measure ?? '')].join(','))
  lines.push(['Rows in view', cell(`${report.row_count} of ${report.spine_total}`)].join(','))
  if (report.graph) {
    lines.push(['Graph', cell(`${report.graph.name} ${report.graph.version ?? ''}`.trim())].join(','))
    lines.push(['Graph sha256', cell(report.graph.sha256 ?? '')].join(','))
  }
  /* A generated report's tiles are recomputed and its horizon is declared rather than applied.
     Both are stated on screen, so both belong in a file that stands in for the screen. */
  lines.push(['Variant', cell(report.variant ?? '')].join(','))

  for (const block of report.blocks ?? []) {
    if (!TABULAR.has(block.type)) continue
    lines.push('')
    lines.push(cell(block.title))
    if (block.sorted_by) lines.push(cell(`Ordered by ${block.sorted_by}`))
    lines.push((block.columns ?? []).map((c) => cell(c.label)).join(','))
    for (const row of block.rows ?? []) {
      lines.push((block.columns ?? []).map((c) => cell(row[c.key])).join(','))
    }
  }

  for (const caveat of report.caveats ?? []) {
    lines.push('')
    lines.push(cell(`Caveat: ${caveat}`))
  }

  /* CRLF, because that is what RFC 4180 says and what Excel expects for a file it did not write. */
  return `${lines.join('\r\n')}\r\n`
}

/* ---------------- HTML ---------------- */

/**
 * A bar, drawn as a div.
 *
 * Hand-drawn, like every other chart in this app — and a div rather than an SVG because an SVG
 * scales its text with the drawing, which is the trap already recorded for the answer charts. The
 * bar encodes magnitude by length; **the value is printed beside it** so nothing is length-only,
 * which is the same rule the on-screen charts keep with their collapsed values table.
 */
const bars = (data) => {
  const max = Math.max(...data.map((d) => Math.abs(Number(d.value) || 0)), 0)
  return data
    .map((d) => {
      const v = Number(d.value) || 0
      const pct = max > 0 ? Math.abs(v) / max : 0
      return `<tr><th scope="row">${esc(d.label)}</th><td class="b"><span style="width:${(
        pct * 100
      ).toFixed(1)}%"></span></td><td class="v">${esc(
        typeof d.value === 'number' ? d.value.toLocaleString('en-US') : d.value,
      )}</td>${d.tier ? `<td class="t">${esc(d.tier)}</td>` : '<td class="t"></td>'}</tr>`
    })
    .join('')
}

const table = (block) => {
  const cols = block.columns ?? []
  const head = cols.map((c) => `<th scope="col">${esc(c.label)}</th>`).join('')
  const body = (block.rows ?? [])
    .map((row) => {
      /* The subject row of a scorecard is marked, as it is on screen — a comparison whose subject
         is not identifiable is a list. */
      const isSubject = block.subject && cols[0] && row[cols[0].key] === block.subject
      const cells = cols
        .map((c) => {
          const v = row[c.key]
          const num = c.kind === 'number' || typeof v === 'number'
          return `<td${num ? ' class="n"' : ''}>${esc(
            typeof v === 'number' ? v.toLocaleString('en-US') : v,
          )}</td>`
        })
        .join('')
      return `<tr${isSubject ? ' class="subject"' : ''}>${cells}</tr>`
    })
    .join('')
  return `<table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`
}

const chart = (block) => {
  const rows = bars(block.data ?? [])
  const companion = block.companion
    ? `<h4>${esc(block.companion.title)}</h4>${
        block.companion.note ? `<p class="note">${esc(block.companion.note)}</p>` : ''
      }<table class="bars"><tbody>${bars(block.companion.data ?? [])}</tbody></table>`
    : ''
  return `<table class="bars"><caption class="sr">${esc(block.y_label ?? '')}</caption><tbody>${rows}</tbody></table>${
    block.note ? `<p class="note">${esc(block.note)}</p>` : ''
  }${companion}`
}

/**
 * The whole report as one self-contained page.
 *
 * Self-contained is not a preference: the file is written to a bucket and opened through a
 * presigned URL, where a stylesheet or a font on another host would be a request the viewer's
 * browser makes to somewhere they were never told about — and, in a private bucket, one that
 * would simply fail. Everything is inline.
 */
export function toHtml(report, { generatedAt, generatedBy } = {}) {
  const tiles = (report.tiles ?? [])
    .map(
      (t) =>
        `<div class="tile"><div class="tl">${esc(t.label)}</div><div class="tv">${esc(
          t.value,
        )}</div>${t.unit ? `<div class="tu">${esc(t.unit)}</div>` : ''}</div>`,
    )
    .join('')

  const blocks = (report.blocks ?? [])
    .map((b) => {
      const body = b.type === 'chart' ? chart(b) : TABULAR.has(b.type) ? table(b) : ''
      if (!body) return ''
      return `<section class="block"><h3>${esc(b.title)}</h3>${
        b.sorted_by ? `<p class="note">Ordered by ${esc(b.sorted_by)}.</p>` : ''
      }${body}</section>`
    })
    .join('')

  const footer = (report.footer ?? [])
    .map((f) => `<div><dt>${esc(f.label)}</dt><dd>${esc(f.text)}</dd></div>`)
    .join('')

  const caveats = (report.caveats ?? []).map((c) => `<li>${esc(c)}</li>`).join('')

  return `<title>${esc(report.heading)}</title>
<style>
  :root { --ink:#1b1b1b; --dim:#5c5c5c; --line:#e3e3e3; --brand:#f4562b; --wash:#faf7f5; }
  * { box-sizing:border-box }
  body { margin:0; padding:32px; font:14px/1.55 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
         color:var(--ink); background:#fff; max-width:1100px }
  h1 { font-size:26px; margin:0 0 4px }
  h3 { font-size:16px; margin:0 0 10px; padding-bottom:6px; border-bottom:2px solid var(--brand) }
  h4 { font-size:14px; margin:20px 0 8px; color:var(--dim) }
  .badge { display:inline-block; padding:2px 10px; border:1px solid var(--brand); color:var(--brand);
           border-radius:12px; font-size:11px; letter-spacing:.06em; text-transform:uppercase }
  .sub { color:var(--dim); margin:8px 0 0; max-width:75ch }
  .note { color:var(--dim); font-size:12px; margin:6px 0 0; max-width:80ch }
  .meta { margin:20px 0; padding:12px 14px; background:var(--wash); border-left:3px solid var(--brand); font-size:12px }
  .meta b { font-weight:600 }
  .tiles { display:flex; flex-wrap:wrap; gap:12px; margin:20px 0 }
  .tile { flex:1 1 150px; border:1px solid var(--line); border-radius:6px; padding:10px 12px }
  .tl { font-size:11px; color:var(--dim); text-transform:uppercase; letter-spacing:.05em }
  .tv { font-size:22px; font-weight:600; margin-top:2px }
  .tu { font-size:11px; color:var(--dim) }
  .block { margin:26px 0; page-break-inside:avoid }
  table { border-collapse:collapse; width:100%; font-size:13px }
  th,td { text-align:left; padding:6px 9px; border-bottom:1px solid var(--line); vertical-align:top }
  thead th { background:var(--wash); font-size:11px; text-transform:uppercase; letter-spacing:.05em; color:var(--dim) }
  td.n, td.v { text-align:right; font-variant-numeric:tabular-nums; white-space:nowrap }
  tr.subject { background:#fff5f1; font-weight:600 }
  table.bars th { font-weight:400; width:34% }
  table.bars td.b { width:50% }
  table.bars td.b span { display:block; height:13px; background:var(--brand); border-radius:2px; min-width:1px }
  table.bars td.t { color:var(--dim); font-size:11px; white-space:nowrap }
  .sr { position:absolute; width:1px; height:1px; overflow:hidden; clip:rect(0 0 0 0) }
  dl { display:grid; grid-template-columns:1fr 1fr; gap:10px 24px; margin:0 }
  dt { font-size:11px; text-transform:uppercase; letter-spacing:.05em; color:var(--dim) }
  dd { margin:2px 0 0 }
  .caveats { margin:24px 0 0; padding:12px 14px; border:1px solid var(--line); border-radius:6px }
  .caveats h4 { margin:0 0 6px }
  .caveats li { color:var(--dim); font-size:12px; margin-bottom:4px }
  footer { margin-top:28px; padding-top:14px; border-top:1px solid var(--line); font-size:11px; color:var(--dim) }
  @media print {
    body { padding:0; max-width:none }
    .block { page-break-inside:avoid }
    thead { display:table-header-group }
  }
</style>
<h1>${esc(report.heading)}</h1>
${report.badge ? `<span class="badge">${esc(report.badge)}</span>` : ''}
${report.subtitle ? `<p class="sub">${esc(report.subtitle)}</p>` : ''}
${report.note ? `<p class="note">${esc(report.note)}</p>` : ''}

<div class="meta">
  <div><b>Generated</b> ${esc(generatedAt ?? '')}${generatedBy ? ` by ${esc(generatedBy)}` : ''}</div>
  ${report.question ? `<div><b>Question</b> ${esc(report.question)}</div>` : ''}
  ${report.reading ? `<div><b>Reading</b> ${esc(report.reading)}</div>` : ''}
  <div><b>Rows</b> ${esc(report.row_count)} of ${esc(report.spine_total)}${
    report.variant ? ` · ${esc(report.variant)}` : ''
  }</div>
  ${
    report.graph
      ? `<div><b>Graph</b> ${esc(report.graph.name)} ${esc(report.graph.version ?? '')} · <code>${esc(
          String(report.graph.sha256 ?? '').slice(0, 16),
        )}</code></div>`
      : ''
  }
</div>

${tiles ? `<div class="tiles">${tiles}</div>` : ''}
${report.summary_note ? `<p class="note">${esc(report.summary_note)}</p>` : ''}
${blocks}
${
  caveats
    ? `<div class="caveats"><h4>Read this under</h4><ul>${caveats}</ul></div>`
    : ''
}
${footer ? `<footer><dl>${footer}</dl></footer>` : ''}
<footer>${esc(report.source_trace ?? '')}</footer>
`
}

/** What each format is called on the way out — one place, so the route and the key agree. */
export const FORMATS = {
  html: { ext: 'html', contentType: 'text/html; charset=utf-8', render: toHtml },
  csv: { ext: 'csv', contentType: 'text/csv; charset=utf-8', render: toCsv },
}
