"""AI Submissions — the Keolis Valmont version of the DB object in ai_submissions_deliverables_demo_9.html.

Same top-level keys and field shapes as the prototype's DB, so the page can read it unchanged in
structure. Two engine ids are renamed because they carried US-water meaning:
  prototype `example: 'dsic_filing'` → `eligibility_filing` (the PPI claim: candidates × rules)
  prototype `example: 'board_deck'`  → `review_deck` (the investment-committee review deck)
See `_engine_notes` in the output for what buildFiling / filingCompute must read instead."""
from world import *

KV_DOCS = ["DSP-VM-2021_Contrat_extraits_Art12_Art34_Annexe7.pdf", "DSP-VM-2021-AV2_Avenant_2_GER_Art34-4.pdf", "DSP-VM-2021-AV3_Avenant_3_Annexe7_BUS209-216.pdf",
           "PPI_2024-2028_Quarterly_Review_Q2-2026_Minutes.pdf", "Convention PPI 2024-2028 VM-PPI-2024.pdf", "Rapport annuel du délégataire 2025 (as submitted).pdf",
           "Claim CLM-2026-Q2 (as submitted).xlsx", "Instruction budgétaire Keolis France 2026.docx", "Comité d'investissement — Q2 2026 review.pptx",
           "Forecast R2 July 2026.xlsx", "Convention de subvention AAP TCSP 2024 — e-bus & charging.pdf", "Rapport annuel de sécurité 2025 (STPG).pdf",
           "PPI_claims_tracker_Q3_working.xlsx", "Capital renewal mailbox export Sep 2026.mbox"]

def build():
    P = PBY
    return {
      "_about": "Keolis Valmont AI Submissions data. Hypothetical: the operator, the authority, the contract and all figures are invented for the ContextWeave demo. Same keys as the prototype DB object.",
      "_engine_notes": {
        "eligibility_filing": "Replaces the prototype's 'dsic_filing' engine. filingCompute(s) should sum `cost` over projects whose decision is 'include' (claimable milestones), and test that sum against params.annualEnvelope − params.claimedYTD (the PPI appropriation still open this year) instead of the prototype's revenue-requirement × fixed-charge-rate cap. params.minSpend is the convention's minimum quarterly claim. Rule ids are in DB.rules; the prototype's string tests on 'before_test_year' and rule.startsWith('class') map to 'already_claimed' and 'ger_funded'.",
        "review_deck": "Replaces the prototype's 'board_deck' engine. deckCompute reads DB.programme exactly as before; the keys fcJan / fc66 keep their names for shape compatibility and mean forecast round R1 (April) and the current working forecast (R2 + Sep actuals). inService on a project means 'accepted and released for service'.",
        "ids_kept": "Recipient and obligation ids are Keolis-native (vm_aom, strmtg, ci_kf …). The prototype hardcodes 'bpu', 'cic', 'dsic', 'board_q', 'selby3', 'domsvc' in a few strings; those map to 'vm_aom', 'ci_kf', 'ppi_q', 'ci_q', 'tv100_m89', 'bev_acc' here."},
      "today": TODAY,
      "tenant": {"name": "Keolis Valmont", "industry": "Transport & Transit"},
      "asOf": {"gl": CLOSE, "register": "2026-09-19", "approvals": "2026-09-19", "forecast": "2026-07-31", "risk": "2026-09-18", "mail": "2026-09-22"},
      "user": {"id": "nishant", "name": "Nishant Srivastav", "initials": "NS", "role": "Investment Reporting Lead", "title": "Lead, Capital Renewal & Authority Reporting"},
      "people": {"nishant": {"id": "nishant", "name": "Nishant Srivastav", "initials": "NS", "role": "Investment Reporting Lead", "title": "Lead, Capital Renewal & Authority Reporting"},
                 "controls": {"id": "controls", "name": "Amélie Roussel", "initials": "AR", "role": "Investment Controller", "title": "Contrôleuse de gestion investissements, Keolis Valmont"}},
      "formats": {"filing_package": {"label": "Claim / filing package", "ico": "§", "files": "PDF + one CSV per schedule", "renders": "schedules and narrative", "ext": "pdf"},
                  "deck": {"label": "Presentation", "ico": "▭", "files": "PPTX (speaker notes inside)", "renders": "slides with cited figures", "ext": "pptx"},
                  "document": {"label": "Document", "ico": "¶", "files": "DOCX", "renders": "sections with tables and narrative", "ext": "docx"},
                  "workbook": {"label": "Workbook", "ico": "⊞", "files": "XLSX (one sheet per schedule)", "renders": "schedules only", "ext": "xlsx"}},
      "kinds": {
        "Regulatory": {"label": "Regulatory & legal reporting", "who": "Préfet and STRMTG (guided-transport safety) · the organising authority as the legal recipient of the delegate's annual report", "basis": "Regime — the law or regulation each obligation comes from", "scopeStep": "Which regimes apply", "cls": "blue",
                       "hint": "Reports the operator owes by law on the network it runs: the delegate's annual report, the guided-transport safety report, accessibility progress.", "name": "Regulatory & legal reporting",
                       "desc": "Everything Keolis Valmont must report by law about the network it operates — the annual delegate report (RAD) with its asset inventory and renewal programme, the annual safety report for the tram, and accessibility progress.",
                       "web": True, "webNote": "Legifrance texts and regulator guidance. Lowest authority; used to confirm, never to invent.", "research": True,
                       "researchLabel": "Research which regulations apply to an urban public-transport operator under a DSP in France",
                       "corpusDocs": ["Rapport annuel du délégataire 2025 (as submitted).pdf", "Rapport annuel de sécurité 2025 (STPG).pdf", "DSP-VM-2021_Contrat_extraits_Art12_Art34_Annexe7.pdf"]},
        "Internal": {"label": "Group capital cycle", "who": "Keolis France investment committee · Keolis Valmont executive committee · group finance", "basis": "Reporting cycle — the committee calendar and the finance calendar", "scopeStep": "Who receives it", "cls": "purple",
                     "hint": "Quarterly investment-committee review, monthly capital pack, forecast rounds (R1 April · R2 July · R3 October), annual budget.", "name": "Group capital cycle",
                     "desc": "What Keolis Valmont owes the Keolis France investment committee, its own executive committee and group finance each cycle: the quarterly review, the monthly pack, the forecast rounds and the annual budget.",
                     "web": False, "webNote": "Public sources do not apply to internal reporting.", "research": False,
                     "corpusDocs": ["Instruction budgétaire Keolis France 2026.docx", "Comité d'investissement — Q2 2026 review.pptx", "Forecast R2 July 2026.xlsx"]},
        "Financial": {"label": "Grants & funding bodies", "who": "State grant programme (via the authority) · regional council", "basis": "Funding agreement — each grant convention", "scopeStep": "Which agreements", "cls": "amber",
                      "hint": "Progress and expenditure statements owed under grant conventions for e-buses and charging.", "name": "Grant reporting",
                      "desc": "Expenditure statements and progress reports owed under the 2024 grant convention for battery-electric buses and depot charging.",
                      "web": False, "webNote": "Public sources do not apply; the convention is the only authority.", "research": False,
                      "corpusDocs": ["Convention de subvention AAP TCSP 2024 — e-bus & charging.pdf"]},
        "Contractual": {"label": "Authority reporting (DSP)", "who": "Valmont Métropole — the organising authority under contract DSP-VM-2021", "basis": "Contract — DSP-VM-2021, its amendments and the PPI convention", "scopeStep": "Which contracts", "cls": "green",
                        "hint": "What the contract makes Keolis Valmont send the authority: quarterly PPI claims, the quarterly PPI review, the asset inventory, Article 34.4 notices.", "name": "Authority reporting",
                        "desc": "Quarterly PPI reimbursement claims and review packs owed to Valmont Métropole, the annual Annex 7 inventory update and Article 34.4 notices.",
                        "web": False, "webNote": "Public sources do not apply; the contract is the authority.", "research": False,
                        "corpusDocs": ["DSP-VM-2021_Contrat_extraits_Art12_Art34_Annexe7.pdf", "DSP-VM-2021-AV2_Avenant_2_GER_Art34-4.pdf", "DSP-VM-2021-AV3_Avenant_3_Annexe7_BUS209-216.pdf", "Convention PPI 2024-2028 VM-PPI-2024.pdf", "Claim CLM-2026-Q2 (as submitted).xlsx"]},
        "Other": {"label": "Other", "who": "Anyone you name", "basis": "Recipient — declared by you", "scopeStep": "Who receives it", "cls": "gray",
                  "hint": "A family of deliverables the library has no standard templates for. You name the recipients and declare what you owe; the templates are the documents you upload or compose.",
                  "name": "", "desc": "", "web": False, "webNote": "Public sources do not apply.", "research": False, "corpusDocs": []},
      },
      "corpus": {"source": "Google Drive — Keolis Valmont Capital Renewal (connected)", "files": KV_DOCS},
      "jurisdictions": [
        {"code": "STPG", "label": "Guided transport safety (tram T1, T2)", "projects": 17, "share": "45%", "recipients": [
            {"id": "strmtg", "short": "Préfet / STRMTG", "name": "Préfet de département, with the STRMTG (Service technique des remontées mécaniques et des transports guidés)", "role": "Safety authority for guided transport", "needs": "A safety report it can audit: incidents, changes to the system, renewals that affect safety, each backed by a record.", "channel": "Transmission to the préfet, copy to the STRMTG regional office", "ev": "Décret 2017-440 — public source, confirm"}]},
        {"code": "DSP", "label": "Delegated public service (whole network)", "projects": 38, "share": "100%", "recipients": [
            {"id": "vm_aom", "short": "Valmont Métropole", "name": "Valmont Métropole — Direction des mobilités", "role": "Organising authority (AOM) and legal recipient of the delegate's annual report", "needs": "Accounts, service quality, the asset inventory and the renewal programme — every figure traceable to the contract and the ledger.", "channel": "Annual report by 1 June; quarterly PPI review", "ev": "Code de la commande publique — public source"}]},
        {"code": "ACC", "label": "Accessibility (stations and stops)", "projects": 5, "share": "13%", "recipients": [
            {"id": "acc_aom", "short": "Valmont Métropole (SD'AP)", "name": "Valmont Métropole — accessibility programme owner", "role": "Owner of the accessibility master plan", "needs": "", "channel": "Annual progress statement"}]},
        {"code": "Corp", "label": "Corporate (no regime)", "projects": 4, "share": "11%", "recipients": [], "issue": "Studies and systems with no regime of their own — left out of every regulatory stream."},
      ],
      "recipientSets": {
        "Internal": {"scope": [["Programme", f"The Keolis Valmont renewal portfolio under DSP-VM-2021 ({len(PORTFOLIO)} projects)", "ppm.project"], ["Fiscal year", "Calendar year", "Instruction budgétaire 2026 §1"], ["Forecast rounds", "R1 (April) · R2 (July) · R3 (October)", "Instruction budgétaire 2026 §3"]],
                     "bodies": [{"id": "ci_kf", "short": "Investment committee", "name": "Keolis France — comité d'investissement", "role": "Regional management and group finance; meets quarterly", "needs": "The state of the renewal programme in six slides: delivery, forecast movement against budget, operator exposure, and the decisions requested. Every figure defensible if questioned.", "channel": "Committee portal; papers 10 working days ahead", "ev": "Suggested from the standard template and the prior Q2 review"},
                                {"id": "codir", "short": "Executive committee", "name": "Keolis Valmont — comité de direction", "role": "Directrice générale and direct reports", "needs": "Month-end spend against forecast and delivery status, with the exceptions called out.", "channel": "Monthly pack, circulated by the author", "ev": "Suggested from the library"},
                                {"id": "gf", "short": "Group finance", "name": "Keolis group finance — planning & consolidation", "role": "Group FP&A", "needs": "The forecast on the group template, tying to the project-level forecast, three times a year.", "channel": "Group forecast template (workbook)", "ev": "Suggested from the prior submission found"}]},
        "Financial": {"scope": [["Agreements in the corpus", "1 grant convention found", "your documents"]],
                      "bodies": [{"id": "grant", "short": "Grant programme", "name": "State grant programme (AAP TCSP 2024) — via Valmont Métropole", "role": "Grant managing body", "needs": "Eligible expenditure by item against the convention's schedule, with invoices and acceptance evidence.", "channel": "Expenditure statement through the authority", "ev": "Convention §6"}]},
        "Contractual": {"scope": [["Contracts in the corpus", "1 DSP + 3 amendments + PPI convention", "your documents"]],
                        "bodies": [{"id": "vm_ppi", "short": "Valmont Métropole (PPI)", "name": "Valmont Métropole — PPI lead and finance", "role": "Authority project and finance leads", "needs": "Claims it can check line by line: milestone achieved, acceptance evidence attached, nothing claimed twice, GER work excluded.", "channel": "Quarterly claim and review meeting", "ev": "DSP Art. 34.3 · PPI convention §4"}]},
      },
      "passes": [
        {"id": "template", "label": "Read the template library — your uploads and the standard templates: what each one is, and the deliverable it produces", "found": {"Regulatory": "4 candidates", "Internal": "4 candidates", "Financial": "1 candidate", "Contractual": "4 candidates"}},
        {"id": "doc", "label": "Read your governing documents and prior deliverables", "found": {"Regulatory": "3 documents · 2 prior reports", "Internal": "3 documents · 1 prior review · 1 prior forecast", "Financial": "1 convention", "Contractual": "5 documents · 1 prior claim"}},
        {"id": "research", "label": "Research which regulations apply — codes, decrees, regulator guidance (public sources, lowest authority)", "found": {"Regulatory": "7 texts examined · 3 apply · 2 outside this stream"}},
      ],
      "researchSets": {"Regulatory": [
        {"rule": "Code de la commande publique, art. L3131-5 and R3131-2 to R3131-4 — rapport annuel du délégataire", "finding": "The delegate produces each year, before 1 June, a report to the authority with the accounts of the delegation, an analysis of service quality and, in its annexes, the inventory of assets and the renewal programme.", "applies": "applies", "implies": "rad", "src": "Legifrance — public source"},
        {"rule": "Décret n° 2017-440 (sécurité des transports publics guidés) — annual safety report", "finding": "The operator of a tram system transmits an annual report on the safety of operation to the préfet, with the STRMTG in copy. Confirm article and content with the STRMTG regional office.", "applies": "likely", "implies": "stpg", "src": "Legifrance · STRMTG guidance — public source, confirm"},
        {"rule": "Accessibility master plan (SD'AP) — annual progress", "finding": "Progress on the programmed accessibility works is reported annually by the owner of the programme; Keolis Valmont supplies delivery data for platforms and stops.", "applies": "likely", "implies": "sdap", "src": "Public source — confirm with the authority"},
        {"rule": "Code de l'environnement, art. L224-8 — low-emission bus share at renewal", "finding": "Public bodies managing a fleet of more than 20 buses must buy low-emission buses when renewing. The obligation and its reporting sit with the authority; Keolis Valmont supplies fleet data.", "applies": "scope", "implies": None, "src": "Legifrance — public source"},
        {"rule": "Corporate sustainability reporting", "finding": "Group-level reporting obligation of Keolis; not a Keolis Valmont capital deliverable.", "applies": "scope", "implies": None, "src": "Public source"},
        {"rule": "Handback inventory at contract end (Art. 12.3)", "finding": "Owed at the end of the contract (31 Dec 2028), not in this period.", "applies": "no", "implies": "handback", "src": "DSP-VM-2021 Art. 12.3"},
        {"rule": "Environmental permit reporting for depots (ICPE)", "finding": "No ICPE declaration found for the three depots in the corpus; the Les Aubiers fuel tank leak test is a maintenance record, not a permit report.", "applies": "no", "implies": "icpe", "src": "Public source · your documents"},
      ]},
      "proposalSets": {
        "Regulatory": [
          {"id": "rad", "label": "Rapport annuel du délégataire (RAD) — asset inventory and renewal programme", "to": "vm_aom", "deliv": "rad_report", "match": "Matched on the prior report's structure and the Code", "cadence": "Annual", "stance": "applies",
           "evidence": [["research", "CCP L3131-5 / R3131-2 — annual report before 1 June"], ["prior", "Prior report found: 2025, submitted 28 May 2026"], ["doc", "DSP-VM-2021 Art. 12.2 — Annex 7 inventory kept current"]]},
          {"id": "stpg", "label": "Annual safety report — guided transport (tram)", "to": "strmtg", "deliv": "safety_report", "match": "Matched on the decree and the prior report", "cadence": "Annual", "stance": "likely",
           "evidence": [["research", "Décret 2017-440 — annual safety report to the préfet (confirm)"], ["prior", "Prior report found: 2025"]]},
          {"id": "sdap", "label": "Accessibility programme — annual progress statement", "to": "acc_aom", "deliv": "sdap_statement", "match": "Matched on the programme; no prior statement in the corpus", "cadence": "Annual", "stance": "likely",
           "evidence": [["research", "SD'AP annual progress (confirm with the authority)"], ["doc", "No prior statement found — first one drafted from the register"]]},
          {"id": "handback", "label": "Handback inventory", "to": "vm_aom", "deliv": "handback_inventory", "match": "Standard template", "cadence": "At contract end", "stance": "no",
           "evidence": [["doc", "Contract ends 31 Dec 2028 — not due in this period"]]},
        ],
        "Internal": [
          {"id": "ci_q", "label": "Investment committee review", "to": "ci_kf", "deliv": "ci_review_deck", "match": "Matched on the recipient, the quarterly cadence and the prior review's six-slide shape", "cadence": "Quarterly", "stance": "applies",
           "evidence": [["template", "Standard template: investment committee review deck"], ["prior", "Prior review found: Q2 2026, circulated 10 Jul 2026"]]},
          {"id": "monthly", "label": "Monthly capital pack", "to": "codir", "deliv": "monthly_pack", "match": "Matched on the cadence and the recipient", "cadence": "Monthly", "stance": "applies",
           "evidence": [["template", "Standard template: monthly capital pack"], ["doc", "Instruction budgétaire 2026 §2 — pack by working day 7"]]},
          {"id": "fcst", "label": "Forecast round (R1 · R2 · R3)", "to": "gf", "deliv": "forecast_sub", "match": "Matched on the group template found in the prior submission", "cadence": "Three per year", "stance": "applies",
           "evidence": [["doc", "Instruction budgétaire 2026 §3 — rounds in April, July and October"], ["prior", "Prior submission found: R2, 31 Jul 2026"]]},
          {"id": "budget", "label": "Annual capital budget — committee paper", "to": "ci_kf", "deliv": "budget_paper", "match": "Matched on the recipient and the budget instruction", "cadence": "Annual", "stance": "applies",
           "evidence": [["doc", "Instruction budgétaire 2026 §6 — 2027 budget to the committee in November"]]},
          {"id": "weekly", "label": "Weekly project status email", "to": "codir", "deliv": None, "match": None, "cadence": "Weekly", "stance": "no",
           "evidence": [["prior", "Found in the mailbox — no recipient outside the team and no record kept. A question for Ask, not a deliverable."]]},
        ],
        "Financial": [
          {"id": "grant_stmt", "label": "Grant expenditure statement — e-bus & charging", "to": "grant", "deliv": "grant_statement", "match": "Matched on the convention", "cadence": "Semi-annual", "stance": "applies",
           "evidence": [["doc", "Convention §6 — semi-annual statement within 60 days of each half-year"], ["template", "Standard template: grant expenditure statement"]]},
        ],
        "Contractual": [
          {"id": "ppi_q", "label": "Quarterly PPI reimbursement claim", "to": "vm_ppi", "deliv": "ppi_claim", "match": "Matched on the prior claim's schedules and the convention", "cadence": "Quarterly", "stance": "applies",
           "evidence": [["doc", "DSP Art. 34.3 — reimbursement on quarterly claims with evidence"], ["prior", "Prior claim found: CLM-2026-Q2, submitted 15 Jul 2026"], ["doc", "PPI convention §4 — claim within 15 days of quarter end"]]},
          {"id": "ppi_review", "label": "Quarterly PPI review pack", "to": "vm_ppi", "deliv": "ppi_review_pack", "match": "Matched on the prior minutes", "cadence": "Quarterly", "stance": "applies",
           "evidence": [["prior", "Prior review minutes found: Q2 2026, 7 Jul 2026"]]},
          {"id": "annex7", "label": "Annex 7 inventory update", "to": "vm_aom", "deliv": "annex7_update", "match": "Matched on the contract", "cadence": "Annual", "stance": "applies",
           "evidence": [["doc", "DSP Art. 12.2 — inventory kept current; AV3 changed eight replacement dates"]]},
          {"id": "notice344", "label": "Article 34.4 notice", "to": "vm_aom", "deliv": "notice_344", "match": "Matched on the clause", "cadence": "Per event (within 30 days)", "stance": "applies",
           "evidence": [["doc", "AV2 Art. 34.4.2 — written notice within 30 days of the failure"], ["prior", "Prior notice found: KV-DIR-2026-0412 (BUS-204)"]]},
        ],
        "Other": [],
      },
      "paramRows": {
        "ppi_q": [["Convention", "VM-PPI-2024 (PPI 2024–2028)", "PPI convention"], ["2026 PPI appropriation", "€24,600,000", "Convention Annex 2 — 2026 line"], ["Claimed to date in 2026", "€16,590,000", "fin.funding_claim — Q1 + Q2"],
                  ["Minimum claim", "€250,000 per quarter", "Convention §4.3"], ["Filing lag after quarter end", "15 days", "Convention §4"], ["Eligible scope", "Renewal of Annex 7 assets under delegated project management; excludes GER and public-network works", "DSP Art. 34.3 · convention §2"]],
        "rad": [["Next due", "1 Jun 2027", "CCP R3131-2 (research) · prior report 28 May 2026"], ["Last submitted", "28 May 2026", "Prior report"]],
        "stpg": [["Next due", "30 Jun 2027", "Prior report cycle (public source; confirm with STRMTG)"], ["Signatory", "SAFETYMGR", "The decree names the operator. Not in any document — you decide who signs."]],
        "sdap": [["Next due", "31 Mar 2027", "Programme calendar (confirm)"]],
        "ci_q": [["Next committee", "CIDATE", "Not in any document you provided — you decide. The standard review is quarterly."], ["Circulation", "10 working days before the meeting", "Standard for a committee paper"],
                 ["Forecast round", "R2 (as at 31 Jul 2026) + actuals to August", "Latest closed round in the corpus"], ["Commentary threshold", "Movement > €0.5M or > 10% of category budget", "Instruction budgétaire 2026 §4.2"]],
        "monthly": [["Next due", "9 Oct 2026 (working day 7)", "Instruction budgétaire 2026 §2"], ["Cut-off", "Ledger close of the month (M09 on 7 Oct)", "Instruction budgétaire 2026 §2"]],
        "fcst": [["Next round · due", "R3 · 6 Nov 2026", "Instruction budgétaire 2026 §3"], ["Template", "Group forecast template v5", "Prior submission"]],
        "budget": [["Paper due", "20 Nov 2026 for the December committee", "Instruction budgétaire 2026 §6"]],
        "grant_stmt": [["Next due", "28 Feb 2027 (H2 + 60 days)", "Convention §6"]],
        "ppi_review": [["Next review", "8 Oct 2026", "Q2 minutes — next meeting"]],
        "annex7": [["Next due", "31 Jan 2027", "DSP Art. 12.2 (annual practice)"]],
        "notice344": [["Open events", "none pending — BUS-204 notified 29 Jul 2026", "fin / contract register"]],
      },
      "regulator": {"short": "Valmont Métropole", "name": "Valmont Métropole — Direction des mobilités", "portal": "PPI claim portal"},
      "params": {"docket": "VM-PPI-2024", "capPct": 100, "revenues": 24_600_000, "annualEnvelope": 24_600_000, "claimedYTD": 16_590_000, "fixedChargeRate": 1.0,
                 "fixedChargeNote": "not applicable — claims reimburse cost, no return is applied", "testYearEnd": "2026-06-30", "priorClosingPlant": 16_590_000, "minSpend": 250_000,
                 "priorFilingName": "PPI claim CLM-2026-Q2 — 1 Apr – 30 Jun 2026 (as submitted 15 Jul 2026)", "varAbs": 500_000, "varPct": 10, "periodStart": "2026-07-01", "periodEnd": "2026-09-30"},
      "library": {"name": "Templates", "standardDesc": "Standard templates for Transport & Transit — one per deliverable an operator under a delegated public-service contract usually owes: authority claims and reviews, the delegate's annual report, safety reporting, group capital reporting, grant statements. Version 2026.09."},
      "online": {"Regulatory": [
        {"id": "ol_rad", "base": "rad_report", "title": "Rapport annuel du délégataire — content required by R3131-3 and R3131-4 (checklist)", "src": "legifrance.gouv.fr — Code de la commande publique", "found": "The articles L3131-5 refers to", "ext": "docx"},
        {"id": "ol_stpg", "base": "safety_report", "title": "Annual safety report — guided transport (STRMTG guidance template)", "src": "strmtg.developpement-durable.gouv.fr — guides", "found": "STRMTG guidance under décret 2017-440 (confirm)", "ext": "docx"},
        {"id": "ol_sdap", "base": "sdap_statement", "title": "Accessibility programme progress — reporting grid", "src": "ecologie.gouv.fr — accessibilité des transports", "found": "Ministry guidance (confirm with the authority)", "ext": "xlsx"}]},
      "recognise": [["comité|investment committee|review deck", "ci_review_deck"], ["monthly|mensuel", "monthly_pack"], ["forecast|r1|r2|r3", "forecast_sub"], ["budget", "budget_paper"], ["memo", "exec_memo"],
                    ["ppi|claim|remboursement", "ppi_claim"], ["rapport annuel du délégataire|rad", "rad_report"], ["sécurité|safety|stpg", "safety_report"], ["accessibilit|sd'ap|sdap", "sdap_statement"],
                    ["annex 7|annexe 7|inventaire", "annex7_update"], ["34.4|notice|notification", "notice_344"], ["subvention|grant", "grant_statement"], ["review pack|revue ppi", "ppi_review_pack"]],
      "templates": {
        "ppi_claim": {"id": "ppi_claim", "origin": "standard", "example": "eligibility_filing", "kinds": ["Contractual"], "name": "Quarterly PPI reimbursement claim", "format": "filing_package", "formatOptions": ["filing_package", "workbook"],
                      "audience": "Organising authority — PPI lead and finance", "purpose": "Claim reimbursement of renewal milestones achieved in the quarter under delegated project management, with the acceptance evidence behind each line and nothing claimed twice.",
                      "sections": [["S1", "Schedule 1 — milestones claimed this quarter", "schedule"], ["S2", "Schedule 2 — appropriation and cumulative claimed", "schedule"], ["S3", "Schedule 3 — candidates evaluated and not claimed", "schedule"], ["S4", "Covering letter, every figure cited", "narrative"]],
                      "inputs": [["Project register with funding source and stage", "available", "keolis_valmont_ppm.ppm"], ["Acceptance items and release records", "partial", "3 battery packs without acceptance"], ["Ledger actuals to quarter end", "available", "ERP, August close + September increments"],
                                 ["Appropriation, minimum claim, eligible scope", "available", "stream setup, cited to the convention"], ["Prior claim", "available", "archive, CLM-2026-Q2"]],
                      "checks": [["scope", "Eligible scope (renewal under delegated project management; not GER)", "state"], ["prior", "Not claimed in a prior quarter", "state"], ["record", "Milestone achieved in the quarter, with acceptance evidence", "state"],
                                 ["cap", "Within the 2026 PPI appropriation still open", "state"], ["floor", "Minimum quarterly claim met", "advisory"], ["dbl", "No double recovery (Art. 34.4 and grants excluded)", "state"]],
                      "files": ["PPI_claim_Q3_v{v}.pdf", "PPI_claim_S1_v{v}.csv", "PPI_claim_S2_v{v}.csv", "PPI_claim_S3_v{v}.csv"],
                      "genSteps": ["Evaluate 9 candidate lines against the convention rules", "Resolve Schedules 1–3 from the graph (ledger as-of 31 Aug + September, register as-of 19 Sep)", "Run 6 checks declared by the deliverable", "Draft the covering letter with a citation on every figure"],
                      "used": "Used by 3 tenants · updated Sep 2026"},
        "ci_review_deck": {"id": "ci_review_deck", "origin": "standard", "example": "review_deck", "kinds": ["Internal"], "name": "Investment committee review deck", "format": "deck", "formatOptions": ["deck", "document"],
                           "audience": "Investment committee", "purpose": "Give the committee the state of the renewal programme for the quarter: delivery, forecast movement, operator exposure, and the decisions it is asked to take.",
                           "sections": [["D1", "Programme at a glance", "slide"], ["D2", "Accepted and released this quarter", "slide"], ["D3", "Forecast movement — current forecast against budget", "slide"], ["D4", "Risks and decisions requested", "slide", "optional"], ["D5", "Authority recovery outlook", "slide", "optional"], ["D6", "Appendix — sources and as-of", "slide"]],
                           "inputs": [["Project register and acceptance records", "partial", "3 packs without acceptance"], ["Ledger actuals year to date", "available", "ERP, August close"], ["Latest forecast round by category", "available", "R2, 31 Jul 2026"],
                                      ["Risk and change register", "available", "PPM, 19 Sep 2026"], ["Programme correspondence (Gmail mailbox)", "available", "cited as claims only, never as figures"], ["Commentary threshold and committee dates", "available", "stream setup"]],
                           "checks": [["recon", "Actuals reconcile to the ledger close", "state"], ["vintage", "Forecast round stated on every projected figure", "state"], ["varc", "Commentary present for every movement over the threshold", "state"],
                                      ["pis", "Acceptance claims backed by a record", "state"], ["corr", "No figure or status taken from correspondence", "state"], ["prior", "Movement from the prior review shown", "advisory"]],
                           "files": ["Investment_committee_review_v{v}.pptx"],
                           "genSteps": ["Resolve programme figures from the graph (ledger year to date, R2 forecast, register)", "Read the risk register, change requests and the mailbox — correspondence as claims", "Run 6 checks declared by the deliverable", "Draft the slides with a citation on every figure and speaker notes", "Compute the movement from the Q2 review"],
                           "used": "Used by 3 tenants · updated Sep 2026"},
        "rad_report": {"id": "rad_report", "origin": "standard", "kinds": ["Regulatory"], "name": "Rapport annuel du délégataire — assets and renewal", "format": "document", "formatOptions": ["document", "workbook"], "audience": "Organising authority — legal annual report",
                       "purpose": "Asset inventory and renewal programme annexes of the delegate's annual report.", "sections": [["A1", "Inventory of assets (Annex 7) with changes in the year", "schedule"], ["A2", "Renewal programme and expenditure", "schedule"], ["A3", "Narrative", "narrative"]],
                       "inputs": [["Asset register", "available", "eam.asset_register"], ["Renewal expenditure", "available", "fin"], ["Service quality data", "missing", "not connected"]], "checks": [["tie", "Inventory ties to the register", "state"], ["amd", "Amendments in the year reflected (AV3)", "state"]],
                       "files": ["RAD_assets_renewal_v{v}.docx"], "genSteps": [], "noExample": True, "used": "Used by 3 tenants"},
        "safety_report": {"id": "safety_report", "origin": "standard", "kinds": ["Regulatory"], "name": "Annual safety report — guided transport", "format": "document", "formatOptions": ["document"], "audience": "Préfet / STRMTG",
                          "purpose": "Safety-relevant renewals and changes to the tram system in the year, each with its record.", "sections": [["G1", "Safety-relevant renewals and changes", "schedule"], ["G2", "Narrative", "narrative"]],
                          "inputs": [["Change and acceptance records (tram)", "available", ""], ["Incident register", "missing", "not connected"]], "checks": [["rec", "Every change backed by an acceptance record", "state"]],
                          "files": ["Safety_report_v{v}.docx"], "genSteps": [], "noExample": True, "used": "Used by 2 tenants"},
        "sdap_statement": {"id": "sdap_statement", "origin": "standard", "kinds": ["Regulatory"], "name": "Accessibility programme — annual progress", "format": "workbook", "formatOptions": ["workbook", "document"], "audience": "Accessibility programme owner",
                           "purpose": "Platforms and stops made accessible in the year.", "sections": [["P1", "Works completed", "schedule"], ["P2", "Plan for next year", "narrative"]], "inputs": [["Accessibility projects", "available", "P-VM-043, P-VM-068"]],
                           "checks": [["acc", "Completion backed by acceptance", "state"]], "files": ["SDAP_progress_v{v}.xlsx"], "genSteps": [], "noExample": True, "used": "Used by 2 tenants"},
        "handback_inventory": {"id": "handback_inventory", "origin": "standard", "kinds": ["Regulatory", "Contractual"], "name": "Handback inventory", "format": "workbook", "formatOptions": ["workbook"], "audience": "Organising authority",
                               "purpose": "Assets, records, spares and open defects handed back at contract end.", "sections": [["H1", "Assets and condition", "schedule"], ["H2", "Records and spares", "schedule"]], "inputs": [["Asset register", "available", ""]],
                               "checks": [["cov", "Every Annex 7 asset listed", "state"]], "files": ["Handback_inventory_v{v}.xlsx"], "genSteps": [], "noExample": True, "used": "Used by 2 tenants"},
        "monthly_pack": {"id": "monthly_pack", "origin": "standard", "kinds": ["Internal"], "name": "Monthly capital pack", "format": "document", "formatOptions": ["document", "deck"], "audience": "Executive committee",
                         "purpose": "Month-end view of spend, forecast and delivery.", "sections": [["M1", "Spend against forecast", "schedule"], ["M2", "Delivery status", "schedule"], ["M3", "Commentary", "narrative"]],
                         "inputs": [["Ledger actuals", "available", ""], ["Project forecasts", "partial", "4 without a current forecast"]], "checks": [["recon", "Actuals reconcile to the ledger close", "state"]],
                         "files": ["Monthly_capital_pack_v{v}.docx"], "genSteps": [], "noExample": True, "used": "Used by 5 tenants"},
        "forecast_sub": {"id": "forecast_sub", "origin": "standard", "kinds": ["Internal"], "name": "Forecast round — group template", "format": "workbook", "formatOptions": ["workbook"], "audience": "Group finance",
                         "purpose": "Forecast by category and project on the group template.", "sections": [["F1", "Forecast by category", "schedule"], ["F2", "Forecast by project", "schedule"]], "inputs": [["Project forecasts", "partial", "4 without a current forecast"]],
                         "checks": [["tie", "Ties to the project-level forecast", "state"]], "files": ["Forecast_round_v{v}.xlsx"], "genSteps": [], "noExample": True, "used": "Used by 4 tenants"},
        "budget_paper": {"id": "budget_paper", "origin": "standard", "kinds": ["Internal"], "name": "Annual capital budget — committee paper", "format": "document", "formatOptions": ["document", "deck"], "audience": "Investment committee",
                         "purpose": "Annual budget request with programme rationale.", "sections": [["B1", "Budget by category", "schedule"], ["B2", "Rationale", "narrative"], ["B3", "Decisions requested", "narrative"]],
                         "inputs": [["Budget build", "missing", "not started"]], "checks": [["tie", "Ties to the budget build", "state"]], "files": ["Capital_budget_paper_v{v}.docx"], "genSteps": [], "noExample": True, "used": "Used by 3 tenants"},
        "exec_memo": {"id": "exec_memo", "origin": "standard", "kinds": ["Internal", "Other"], "name": "Executive summary memo", "format": "document", "formatOptions": ["document"], "audience": "Any leadership recipient",
                      "purpose": "Two-page memo: headline figures, movement, decision requested.", "sections": [["X1", "Headline figures", "schedule"], ["X2", "Narrative", "narrative"]], "inputs": [["Ledger actuals", "available", ""], ["Latest forecast", "available", ""]],
                      "checks": [["recon", "Figures reconcile to the ledger close", "state"]], "files": ["Executive_memo_v{v}.docx"], "genSteps": [], "noExample": True, "used": "Used by 6 tenants"},
        "grant_statement": {"id": "grant_statement", "origin": "standard", "kinds": ["Financial"], "name": "Grant expenditure statement", "format": "workbook", "formatOptions": ["workbook", "document"], "audience": "Grant managing body",
                            "purpose": "Eligible expenditure by item against the convention schedule, with invoices and acceptance evidence.", "sections": [["V1", "Eligible expenditure by item", "schedule"], ["V2", "Statement wording", "narrative"]],
                            "inputs": [["Ledger", "available", ""], ["Convention schedule", "available", ""]], "checks": [["def", "Each item eligible per the convention", "state"], ["dbl", "Not also claimed under the PPI", "state"]],
                            "files": ["Grant_statement_v{v}.xlsx"], "genSteps": [], "noExample": True, "used": "Used by 2 tenants"},
        "ppi_review_pack": {"id": "ppi_review_pack", "origin": "standard", "kinds": ["Contractual"], "name": "Quarterly PPI review pack", "format": "deck", "formatOptions": ["deck", "document"], "audience": "Organising authority",
                            "purpose": "Delivery, forecast and claim position of every PPI project for the quarterly review.", "sections": [["R1", "Delivery status", "slide"], ["R2", "Forecast and claims", "slide"], ["R3", "Decisions requested of the authority", "slide"]],
                            "inputs": [["Register", "available", ""], ["Claims", "available", ""]], "checks": [["corr", "No figure taken from correspondence", "state"]], "files": ["PPI_review_pack_v{v}.pptx"], "genSteps": [], "noExample": True, "used": "Used by 3 tenants"},
        "annex7_update": {"id": "annex7_update", "origin": "standard", "kinds": ["Contractual"], "name": "Annex 7 inventory update", "format": "workbook", "formatOptions": ["workbook"], "audience": "Organising authority",
                          "purpose": "Assets added, withdrawn and re-dated in the year, with the amendment behind each change.", "sections": [["N1", "Changes in the year", "schedule"]], "inputs": [["Asset register", "available", ""], ["Amendments", "available", "AV3"]],
                          "checks": [["amd", "Each date change cites its amendment", "state"]], "files": ["Annex7_update_v{v}.xlsx"], "genSteps": [], "noExample": True, "used": "Used by 2 tenants"},
        "notice_344": {"id": "notice_344", "origin": "standard", "kinds": ["Contractual"], "name": "Article 34.4 notice", "format": "document", "formatOptions": ["document"], "audience": "Organising authority",
                       "purpose": "Written notice of a heavy-component failure after a vehicle's replacement date, with failure report, diagnosis and quotation, within 30 days.", "sections": [["K1", "Notice", "narrative"], ["K2", "Attachments index", "schedule"]],
                       "inputs": [["Failure event", "available", "eam"], ["Quote", "available", "Drive"]], "checks": [["days", "Sent within 30 days of the failure", "state"], ["cap", "Amount stated against the €35,000 cap", "state"]],
                       "files": ["Notice_34-4_v{v}.docx"], "genSteps": [], "noExample": True, "used": "Used by 1 tenant"},
      },
      "parts": [["schedule", "Schedule", "A table of figures with coordinate, source and as-of on every cell"], ["narrative", "Narrative", "AI-drafted paragraphs; every figure cited"], ["kpi", "KPI slide", "Headline tiles and cited bullets"],
                ["risks", "Risk register", "Risks and decisions; correspondence as claims"], ["evidence", "Evidence index", "Every cited document and record"]],
      "obligations": [], "streams": [],
      "projects": [
        {"id": "tv100_m89", "code": "P-VM-005", "name": "Tram TV-100 overhaul — milestones M8–M9 (trams 105–108 released)", "cls": "Fleet — tram (PPI)", "start": "2026-07-01", "inService": "2026-08-20", "record": "ACC-TV100-105-108", "cost": 2_480_000, "decision": "include", "rule": "eligible"},
        {"id": "b2_acc", "code": "P-VM-014", "name": "Bus renewal tranche 2 — batch 2 accepted (8 buses)", "cls": "Fleet — bus (PPI)", "start": "2026-05-29", "inService": "2026-07-10", "record": "ACC-B2-2026-07-10", "cost": 1_920_000, "decision": "include", "rule": "eligible"},
        {"id": "sst04_dep", "code": "P-VM-017", "name": "SST-04 renewal — rectifier order deposit", "cls": "Power & charging (PPI)", "start": "2026-07-14", "inService": "2026-08-05", "record": "INV-ERO-2026-0811", "cost": 460_000, "decision": "include", "rule": "eligible"},
        {"id": "bev_acc", "code": "P-VM-031", "name": "Battery campaign — authority 40% for BUS-417, BUS-422, BUS-431", "cls": "Fleet — bus component (MIXED)", "start": "2026-08-01", "inService": "2026-09-18", "record": None, "cost": 138_000, "decision": "cannot_evaluate", "rule": "no_record"},
        {"id": "t1_works", "code": "P-VM-008", "name": "T1 track renewal — rail replacement works", "cls": "Track & civil (PPI)", "start": "2026-10-12", "inService": None, "forecast": "2026-11-20", "record": None, "cost": 380_000, "decision": "exclude", "rule": "after_period"},
        {"id": "lift_c", "code": "P-VM-021", "name": "Lift replacement Les Aubiers — columns delivered", "cls": "Depot & workshop (GER)", "start": "2026-09-08", "inService": "2026-09-08", "record": "GR-2026-09-08-214", "cost": 160_000, "decision": "exclude", "rule": "ger_funded"},
        {"id": "grid", "code": "P-VM-026", "name": "Charging bank 2 — DSO grid reinforcement share", "cls": "Power & charging (PPI)", "start": "2026-06-19", "inService": None, "forecast": "2026-10-20", "record": None, "cost": 212_000, "decision": "exclude", "rule": "outside_scope"},
        {"id": "frames", "code": "P-VM-005", "name": "TV-100 frame replacement allowance (RC-005-009)", "cls": "Fleet — tram (PPI)", "start": "2026-06-24", "inService": None, "record": None, "cost": 1_320_000, "decision": "exclude", "rule": "not_approved"},
        {"id": "bus204", "code": "N-VM-044", "name": "BUS-204 engine rebuild (Art. 34.4)", "cls": "Fleet — bus (Art. 34.4)", "start": "2026-07-12", "inService": None, "record": None, "cost": 28_000, "decision": "exclude", "rule": "other_mechanism"},
      ],
      "rules": {
        "eligible": {"label": "Eligible", "text": "Renewal of an Annex 7 asset under delegated project management, milestone achieved in the quarter, acceptance or invoice record on file, not claimed before."},
        "no_record": {"label": "Cannot evaluate — no acceptance record", "text": "The three packs are installed but not accepted (two open defects, one missing certificate). An installation is a claim; the line is neither included nor excluded until acceptance is recorded or the author excludes it with a reason."},
        "after_period": {"label": "Milestone after quarter end", "text": "Works start 12 October and finish 20 November, after the quarter closed on 30 September. Belongs to the Q4 claim."},
        "ger_funded": {"label": "GER — inside the contract price", "text": "The lift replacement is major maintenance funded by Keolis Valmont's GER provision under Art. 34.2. Claiming it under the PPI would charge the authority for work already paid in the contract price."},
        "outside_scope": {"label": "Outside the PPI's eligible scope", "text": "The authority reads DSO grid reinforcement as public-network work outside the convention. Disputed since Q2; not re-claimed until the dispute is settled."},
        "not_approved": {"label": "Change not approved", "text": "RC-005-009 is submitted, not approved. A forecast allowance is not a milestone and cannot be claimed."},
        "other_mechanism": {"label": "Recovered under another mechanism", "text": "A heavy-component repair after the replacement date is recovered under Article 34.4, not the PPI. Including it here would recover it twice — and it is still under review."},
        "already_claimed": {"label": "Claimed in a prior quarter", "text": "Milestones already claimed in Q1 or Q2 are excluded."},
      },
      "programme": {"fy": "FY2026", "budget": 44_500_000, "fcJan": 44_600_000, "fc66": 40_800_000, "actYTD": 23_800_000,
                    "priorPack": {"fc": 44_600_000, "label": "Q2 review (R1 forecast)"},
                    "_key_notes": {"fcJan": "forecast round R1 (April)", "fc66": "current working forecast (R2 + actuals to August)"},
                    "byClass": [
                      {"cls": "Fleet — tram", "budget": 12_400_000, "jan": 12_600_000, "fc": 13_200_000, "note": "Frame replacement allowance for trams 101–112 carried although RC-005-009 is not approved.", "noteSrc": "Controller forecast commentary, 15 Sep 2026"},
                      {"cls": "Fleet — bus", "budget": 14_200_000, "jan": 14_000_000, "fc": 11_500_000, "note": "Tranche 2 batch 3 acceptance payment moves to January 2027 if delivery slips to 21 October.", "noteSrc": "Supplier email 8 Sep 2026 (claim) · procurement"},
                      {"cls": "Power & charging", "budget": 6_800_000, "jan": 6_900_000, "fc": 6_100_000, "note": "DSO energisation moved to 20 October; bank 2 works re-phased.", "noteSrc": "DSO letter, 19 Jun 2026"},
                      {"cls": "Track & civil", "budget": 4_600_000, "jan": 4_600_000, "fc": 3_900_000, "note": "T1 closure not yet approved; €0.7M at risk of moving to 2027.", "noteSrc": "Authority email, 10 Sep 2026 (claim)"},
                      {"cls": "Depot & workshop", "budget": 3_100_000, "jan": 3_200_000, "fc": 3_000_000, "note": None, "noteSrc": None},
                      {"cls": "Stations & passenger info", "budget": 2_100_000, "jan": 2_000_000, "fc": 1_900_000, "note": None, "noteSrc": None},
                      {"cls": "Signalling & systems", "budget": 1_300_000, "jan": 1_300_000, "fc": 1_200_000, "note": None, "noteSrc": None}],
                    "risks": [
                      {"kind": "decision", "text": "Decide RC-005-009 (TV-100 frames): €2.64M requested for 24 trams against a €1.32M allowance for 12; option study to be re-appraised.", "src": "Change request RC-005-009, PPM", "coord": "record", "asOf": "2026-09-19"},
                      {"kind": "risk", "text": "Tranche 2 batch 3 — Arvéa says 21 October is 'realistic'. The ERP still shows 30 September; the email is a claim until procurement records it.", "src": "Email, Arvéa Mobility → Fleet projects, 8 Sep 2026", "coord": "correspondence", "asOf": "2026-09-22"},
                      {"kind": "risk", "text": "T1 closure 17–19 October provisional; decision at the authority's service committee on 1 October.", "src": "Email, Valmont Métropole → Infrastructure projects, 10 Sep 2026", "coord": "correspondence", "asOf": "2026-09-22"}]},
      "submissions": {},
    }

if __name__ == "__main__":
    import json
    d = build()
    inc = [p for p in d["projects"] if p["decision"] == "include"]
    print(len(d), "keys; included", sum(p["cost"] for p in inc), "budget", sum(c["budget"] for c in d["programme"]["byClass"]), "fc", sum(c["fc"] for c in d["programme"]["byClass"]))
