/*
 * ============================================================================
 *  The DDL — written from the model, never by hand
 * ============================================================================
 *
 * `mock-server/db/schema.sql` is generated by `npm run db:schema` and committed, the
 * same way `db.json` is generated and committed: it is the reviewable artefact, and
 * `db:migrate` applies *that file* rather than re-deriving it, so what runs against a
 * database is what somebody read in a diff. `check-docs` regenerates it and fails if
 * the committed file has drifted, which is what stops the two being two answers.
 *
 * ---------------------------------------------------------------------------
 *  What the constraints are for
 * ---------------------------------------------------------------------------
 *
 * The foreign keys are not decoration and they are not ORM habit. Each one is a
 * failure this repo has already had, where nothing threw and the screen simply
 * answered wrongly:
 *
 *   canvas_edges.from_node → canvas_nodes    20 edges named ids the roster omitted,
 *                                            so 17 facilities appeared to have no
 *                                            enforcement. A renderer skips what it
 *                                            cannot draw.
 *   template_personas.persona_id → …         a template member that resolves to
 *                                            nothing drops out of the bundle, and the
 *                                            step drafts five personas where the use
 *                                            case names six.
 *   governance_audience.role_id → auth_roles an audience naming a persona that does
 *                                            not exist tells a reader somebody can
 *                                            open a report.
 *   governance_reports.status → statuses     a status the pool does not declare prints
 *                                            its raw key and matches no chip.
 *   column_profiles → dataset_tables         a profile for a table the catalogue does
 *                                            not list is the drift check-docs counts.
 *
 * `validateDb` still checks every one of these in the server, because the `/db` editor
 * and the ingest scripts hand it whole documents that have never been near a database.
 * The constraint is the second line, and it is the one that cannot be forgotten.
 *
 * The keys are emitted as `ALTER TABLE … ADD CONSTRAINT` after every table exists, so
 * the file does not depend on declaration order — but the *insert* order does, so
 * `assertInsertable()` proves the model is topologically sorted and fails loudly if a
 * new table references one declared after it.
 */

import { tableOrder, SPECS } from './mapping.mjs'
import { SCHEMA } from './model.mjs'

const q = (name) => `"${name}"`
const qual = (table) => `${q(SCHEMA)}.${q(table)}`

/**
 * Every foreign key in the model, flattened.
 *
 * A spec's `fk` names the columns, the table and the columns it points at — the same
 * three things the ALTER statement needs and the same three the insert order check
 * reads.
 */
export function foreignKeys() {
  const out = []
  for (const spec of tableOrder()) {
    for (const fk of spec.fk ?? []) {
      out.push({
        name: `${spec.table}_${fk.cols.join('_')}_fkey`,
        table: spec.table,
        cols: fk.cols,
        refTable: fk.table,
        refCols: fk.refs,
      })
    }
  }
  return out
}

/**
 * Refuse a model whose tables cannot be inserted in `tableOrder()`.
 *
 * `commitDb` writes every table in this order inside one transaction and deletes in
 * the reverse, so a table referencing one declared later would fail on the *first*
 * write against a real database — after the model, the mapper and the round-trip check
 * had all passed. Catching it here makes it a `db:schema` failure instead.
 */
export function assertInsertable() {
  const position = new Map(tableOrder().map((s, n) => [s.table, n]))
  const problems = []
  for (const fk of foreignKeys()) {
    if (!position.has(fk.refTable)) {
      problems.push(`${fk.table}.${fk.cols.join(',')} points at "${fk.refTable}", which is not a table`)
      continue
    }
    /* A self-reference is fine — a row can point at another row in its own table. */
    if (fk.refTable === fk.table) continue
    if (position.get(fk.refTable) > position.get(fk.table)) {
      problems.push(
        `${fk.table} references ${fk.refTable}, which is created and inserted after it — ` +
          `move its root earlier in ROOTS`,
      )
    }
  }
  if (problems.length > 0) {
    throw new Error(`mock-server/db/model.mjs is not insertable in order:\n  · ${problems.join('\n  · ')}`)
  }
}

function createTable(spec) {
  const lines = []
  for (const c of spec._columns) {
    const notNull = spec.pk?.includes(c.name) ? ' NOT NULL' : ''
    const check = c.role === 'singleton' ? ` CHECK (${q(c.name)} = 1)` : ''
    lines.push(`  ${q(c.name)} ${c.type}${notNull}${check}`)
  }
  if (spec.pk?.length) {
    lines.push(`  CONSTRAINT ${q(`${spec.table}_pkey`)} PRIMARY KEY (${spec.pk.map(q).join(', ')})`)
  }
  return `CREATE TABLE ${qual(spec.table)} (\n${lines.join(',\n')}\n);`
}

/** The whole schema, as one script. Idempotent: it drops the schema and rebuilds it. */
export function schemaSql() {
  assertInsertable()

  const out = []
  out.push('--')
  out.push('-- ContextWeave — the relational shape of mock-server/db.json.')
  out.push('--')
  out.push('-- GENERATED FILE. Do not edit: run `npm run db:schema` after changing')
  out.push('-- mock-server/db/model.mjs. `npm run check-docs` fails if the two disagree.')
  out.push('--')
  out.push('-- Applied by `npm run db:migrate`. Dropping the schema is how a rebuild starts,')
  out.push('-- because the seed is a whole document rather than a set of changes.')
  out.push('--')
  out.push('')
  out.push(`DROP SCHEMA IF EXISTS ${q(SCHEMA)} CASCADE;`)
  out.push(`CREATE SCHEMA ${q(SCHEMA)};`)
  out.push('')

  for (const spec of tableOrder()) {
    out.push(createTable(spec))
    out.push('')
  }

  out.push('--')
  out.push('-- Foreign keys. Each one is a failure that used to answer instead of throwing;')
  out.push('-- see the note at the top of mock-server/db/schema.mjs.')
  out.push('--')
  out.push('')
  for (const fk of foreignKeys()) {
    out.push(
      `ALTER TABLE ${qual(fk.table)} ADD CONSTRAINT ${q(fk.name)}\n` +
        `  FOREIGN KEY (${fk.cols.map(q).join(', ')}) ` +
        `REFERENCES ${qual(fk.refTable)} (${fk.refCols.map(q).join(', ')});`,
    )
  }
  out.push('')

  /*
   * One index per foreign key on the referencing side. PostgreSQL indexes the
   * referenced columns (they are a key) but not the referencing ones, and every read
   * here is a child lookup by parent id — 241 edges by node, 206 profiles by table.
   */
  out.push('-- A child is always read by its parent key, and PostgreSQL does not index that side.')
  out.push('')
  for (const fk of foreignKeys()) {
    out.push(
      `CREATE INDEX ${q(`${fk.name}_idx`)} ON ${qual(fk.table)} (${fk.cols.map(q).join(', ')});`,
    )
  }
  out.push('')

  return `${out.join('\n')}`
}

export { SCHEMA, SPECS }
