/*
 * Applies mock-server/db/schema.sql. `npm run db:migrate`
 *
 * **It drops the schema and rebuilds it**, and that is deliberate rather than a
 * shortcut. There is no migration history here because there is nothing to migrate
 * *from*: the seed is a whole document (`db.json`, itself regenerated by the ingest
 * scripts from the demo package), so the honest operation is "make the schema match
 * the model, then re-seed" — not "apply the changes since last time" over data that is
 * regenerated anyway.
 *
 * The consequence is stated rather than left to be discovered: migrating empties the
 * database, so `db:seed` follows it every time.
 */

import { readFileSync } from 'node:fs'

import { migrate, connectionAdvice, closePool, target, SCHEMA_PATH, SCHEMA } from '../mock-server/db/pg.mjs'
import { schemaSql } from '../mock-server/db/schema.mjs'

/*
 * The committed file is what gets applied — but if it has drifted from the model, the
 * database would be built to a shape the mapper does not write. Saying so here costs a
 * string compare and turns a baffling insert error into one line.
 */
const onDisk = readFileSync(SCHEMA_PATH, 'utf8')
if (onDisk !== schemaSql()) {
  console.error(
    '\ndb:migrate refused — mock-server/db/schema.sql no longer matches mock-server/db/model.mjs.\n' +
      '  Regenerate it, read the diff, and migrate again:\n      npm run db:schema\n',
  )
  process.exit(1)
}

try {
  const { tables } = await migrate()
  console.log(
    `db:migrate — applied schema "${SCHEMA}" on ${target()}: ${tables} tables.\n` +
      '  The schema was dropped and rebuilt, so it is empty. Next: npm run db:seed',
  )
} catch (error) {
  console.error(`\ndb:migrate failed — ${connectionAdvice(error)}\n`)
  process.exitCode = 1
} finally {
  await closePool()
}
